sudo: false
language: node_js
cache: npm

matrix:
  include:
    - os: linux
      dist: bionic
      node_js: "10"
    - os: osx
      osx_image: xcode11
      node_js: "10"
    - os: linux
      dist: bionic
      node_js: "11"
    - os: osx
      osx_image: xcode11
      node_js: "11"
    - os: linux
      dist: bionic
      node_js: "12"
    - os: osx
      osx_image: xcode11
      node_js: "12"

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - cmake
      - libx11-dev
      - zlib1g-dev
      - libpng-dev
      - libxtst-dev
      - g++-4.8
      - gcc-4.8

services:
  - xvfb

before_install:
  - node --version
  - npm --version

  - if [[ $TRAVIS_OS_NAME == "linux" ]]; then export CXX=g++-4.8; fi
  - $CXX --version

# before_script:
  # Start xvfb
  # - if [[ $TRAVIS_OS_NAME == "linux" ]]; then export DISPLAY=:99.0; fi
  # - if [[ $TRAVIS_OS_NAME == "linux" ]]; then sh -e /etc/init.d/xvfb start; fi

install: true

script:
  - npm run patch && npm i
  - if [[ $TRAVIS_OS_NAME = "windows" ]]; then npm run build:release:win; else npm run build:release; fi
  - xvfb-run npm test

before_deploy:
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" >> $HOME/.npmrc 2> /dev/null

deploy:
  - provider: script
    skip_cleanup: true
    script: npm publish --access public
    on:
      tags: true
      node_js: '12'

