name: Run CI
on:
  push:
    branches-ignore:
      - develop
      - release/**
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        node: [ 10, 12, 14 ]
    runs-on: ${{matrix.os}}
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Set up node
        uses: actions/setup-node@v2
        with:
          node-version: ${{matrix.node}}
      - name: Configure Linux environment
        if: ${{matrix.os == 'ubuntu-latest'}}
        run: |
          sudo apt-get install -y cmake libx11-dev zlib1g-dev libpng-dev libxtst-dev g++-4.8 gcc-4.8
          export CXX=g++-4.8 && $CXX --version
      - name: Install
        run: npm run patch && npm i
      - name: Build
        run: npm run build:release
      - name: Run tests
        uses: GabrielBB/xvfb-action@v1
        with:
          working-directory: ./test/
          run: npm cit
      - name: Run window tests
        uses: GabrielBB/xvfb-action@v1
        with:
          working-directory: ./test/window-integration-tests
          run: npm cit
